spring:
  application:
    name: admin
  cloud:
    loadbalancer:
      health-check:
        refetch-instances: true
        refetch-instances-interval: 2s
  data:
    mongodb:
      database: admin

server:
  port: 0

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: TRACE