spring:
  application:
    name: admin
  cloud:
    loadbalancer:
      health-check:
        refetch-instances: true
        refetch-instances-interval: 2s

server:
  port: 0

eureka:
  instance:
    hostname: localhost
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework: INFO