spring:
  application:
    name: web.emc
  thymeleaf:
    prefix: classpath:/static/
  cloud:
    loadbalancer:
      health-check:
        refetch-instances: true
        refetch-instances-interval: 2s

server:
  port: 0

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka.emc:8761/eureka

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: INFO