spring:
  application:
    name: box
  thymeleaf:
    prefix: classpath:/static/
  cloud:
    loadbalancer:
      health-check:
        refetch-instances: true
        refetch-instances-interval: 2s
  minio:
    url: http://localhost:9000
    bucket: emcrypt
    access-key: myQtfsvyIyDHioJN
    secret-key: Vyeinjyk1HI820fl54RkQfVRalXyz8sF
server:
  port: 0


eureka:
  instance:
    hostname: localhost
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework: INFO