spring:
  application:
    name: gw
  data:
    mongodb:
      database: emcrypt-gw
  cloud:
    loadbalancer:
      health-check:
        refetch-instances: true
        refetch-instances-interval: 2s
  main:
    web-application-type: REACTIVE

eureka:
  instance:
    hostname: localhost
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO