spring:
  application:
    name: comm
  cloud:
    loadbalancer:
      health-check:
        refetch-instances: true
        refetch-instances-interval: 2s
  data:
    mongodb:
      database: emcrypt-comm

server:
  port: 0

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: TRACE


app:
  mail:
    host: mail.olta.la
    port: 25
    auth: false
    ssl: false