spring:
  application:
    name: comm.emc
  cloud:
    loadbalancer:
      health-check:
        refetch-instances: true
        refetch-instances-interval: 2s
  data:
    mongodb:
      database: emcrypt-comm
      host: db.emc

server:
  port: 0

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka.emc:8761/eureka

logging:
  level:
    root: INFO
    org.springframework: INFO


app:
  mail:
    host: mail.olta.la
    port: 25
    auth: false
    ssl: false